from django.contrib.gis.db import models

class School(models.Model):
    school_id = models.IntegerField(
        blank=False, null=False, primary_key=True,
        help_text="ID of the school. (SCH_SCHOOLID)")
    la = models.IntegerField(blank=True, null=True, 
        help_text="""Local Authority (LA) that the school where the pupil 
        attends reports to (original data).""")
    name = models.CharField(blank=True, max_length=255, help_text="SCH_SCHOOLNAME")
    address1 = models.CharField(null=True, blank=True, max_length=255, help_text="SCH_ADDRESS1")
    address2 = models.CharField(null=True, blank=True, max_length=255, help_text="SCH_ADDRESS2")
    address3 = models.CharField(null=True, blank=True, max_length=255, help_text="SCH_ADDRESS3")
    town = models.CharField(null=True, blank=True, max_length=255, help_text="SCH_TOWN")
    county = models.CharField(null=True, blank=True, max_length=255, help_text="SCH_COUNTY")
    postcode = models.CharField(null=True, blank=True, max_length=14, help_text="SCH_POSTCODE")
    URN = models.IntegerField(blank=True, null=True, help_text="School's Unique Reference Number")
    establishment = models.IntegerField(blank=True, null=True, help_text="Establishment number of the school attended as assigned by the DfE")
    establishment_type = models.IntegerField(blank=True, null=True, help_text="Type of establishment code taken from Edubase.")
    nftype = models.CharField(blank=True, max_length=100, help_text="School type")


class PupilData(models.Model):
    class Meta:
        abstract = True
    
    record_id = models.IntegerField(blank=False, null=False, primary_key=True, 
            help_text="Unique record ID - A pseudonymised record ID required for internal purposes.  This ID will not facilitate linking across datasets.")
    school = models.ForeignKey(School)
    la = models.IntegerField(blank=True, null=True, 
        help_text="""Local Authority (LA) that the school where the pupil 
        attends reports to (original data).""")
    gender = models.CharField(blank=True, max_length=1, help_text="KS[n]_GENDER")
    year = models.IntegerField(blank=True, null=True, db_index=True)
    

class KS2(PupilData):
    CVAAPS = models.FloatField(blank=True, null=True, help_text="""KS2 average point score (fg)""")
    ELIGENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil included in the eligible pupil number for English i.e. has a test result of A, B, M, N, P, T, 2-5 or Q.  It is used as the denominator for school and LA calculations of achievement in English.""")
    ELIGMAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil included in the eligible pupil number for Maths i.e. has a test result of A, B, M, N, P, T, 2-5 or Q.  It is used as the denominator for school and LA calculations of achievement in Maths.""")
    ELIGREAD = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil included in the eligible pupil number for Reading i.e. has a test result of A, B, M, N, P, T, 2-5, Q or S.  It is used as the denominator for school and LA calculations of achievement in Reading.""")
    ELIGSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil included in the eligible pupil number for Science i.e. has a test result of A, B, M, N, P, T, 2-5 or Q.  It is used as the denominator for school and LA calculations of achievement in Science.""")
    ELIGWRIT = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil included in the eligible pupil number for Writing i.e. has a test result of A, B, M, N, P, T, 2-5, Q or S.  It is used as the denominator for school and LA calculations of achievement in Writing.""")
    ENGLEV = models.CharField(max_length="10", blank=True, null=True, help_text="""National Curriculum level awarded for English test.""")
    ENGPOINTS = models.CharField(max_length="10", blank=True, null=True, help_text="""English attainment point score.""")
    ENGREADLEV = models.CharField(max_length="10", blank=True, null=True, help_text="""National Curriculum level awarded for English reading test (forms half of overall English test).""")
    ENGWRITLEV = models.CharField(max_length="10", blank=True, null=True, help_text="""National Curriculum level awarded for English writing test (forms half of overall English test).""")
    FLAG2KENG12 = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil flag for making 2 levels of progress in English between KS1 and KS2""")
    FLAG2KMATH12 = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil flag for making 2 levels of progress in maths between KS1 and KS2""")
    KS2APSFG = models.CharField(max_length="10", blank=True, null=True, help_text="""KS2 average point score (fg)""")
    KS2ENGFG = models.CharField(max_length="10", blank=True, null=True, help_text="""KS2 English point score (using fine grading)""")
    KS2MATFG = models.CharField(max_length="10", blank=True, null=True, help_text="""KS2 maths point score (using fine grading)""")
    LEVATENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Absent or unable to access the test in English.""")
    LEVATMAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Absent or unable to access the test in Maths.""")
    LEVATSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Absent or unable to access the test in Science.""")
    LEVAXEMS = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 5 (above expected level) in KS2 English, Maths and Science.""")
    LEVAXENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 5 in KS2 English.""")
    LEVAXMAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 5 in KS2 Maths.""")
    LEVAXREAD = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 5 (above expected level) in KS2 English reading.""")
    LEVAXSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 5 in KS2 Science.""")
    LEVAXWRIT = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 5 (above expected level) in KS2 English writing.""")
    LEVBXENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 3 or below in KS2 English.""")
    LEVBXMAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 3 or below in KS2 Maths.""")
    LEVLEMS = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 2 or below (low attainment) in KS2 English, Maths and Science.""")
    LEVLENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 2 or below (low attainment) in KS2 English""")
    LEVLMAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 2 or below (low attainment) in KS2 Maths.""")
    LEVLSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 2 or below (low attainment) in KS2 Science.""")
    LEVXEMS = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 4 or above (expected level) in KS2 English, Maths and Science.""")
    LEVXENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 4 or above in KS2 English.""")
    LEVXENGMAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 4 or above (expected level) in KS2 English and Maths""")
    LEVXMAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 4 or above in KS2 Maths.""")
    LEVXSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 4 or above in KS2 Science.""")
    MATLEV = models.CharField(max_length="10", blank=True, null=True, help_text="""National Curriculum level awarded for Maths test.""")
    MATPOINTS = models.CharField(max_length="10", blank=True, null=True, help_text="""Maths attainment point score.""")
    PROGENG12 = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of levels of progress in English between KS1 and KS2 (excluding TA)""")
    PROGENG12FLAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil flag for making 2 levels of progress in English between KS1 and KS2""")
    PROGMAT12FLAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil flag for making 2 levels of progress in maths between KS1 and KS2""")
    PROGMATH12 = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of levels of progress in maths between KS1 and KS2""")
    RECORDID = models.CharField(max_length="10", blank=True, null=True, help_text="""Unique record ID - A pseudonymised record ID required for internal purposes.  This ID will not facilitate linking across datasets.""")
    REFTEST = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil KS2 results withheld by school?""")
    SCILEV = models.CharField(max_length="10", blank=True, null=True, help_text="""National Curriculum level awarded for Science test.""")
    SCIPOINTS = models.CharField(max_length="10", blank=True, null=True, help_text="""Science attainment point score.""")
    TOTPTS = models.CharField(max_length="10", blank=True, null=True, help_text="""Total KS2 point score as used in the valued added calculations.""")
    
class KS4(PupilData):
    TWOBTECEDEXDA = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved at least two BTEC First Diploma/Certificates or a combination of EDEXCEL Qualifications in Digital Applications for IT User and BTEC First Diploma/Certificates.""")
    ALLSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered all of Biology, Physics, Chemistry  GCSEs or ASs""")
    ANYLEV1 = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved at least 1 GCSE or equivalent at grade A*-G.""")
    ANYPASS = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved any passes at all in GCSE or equivalents.""")
    ANYPMFL = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved any passes in Modern Foreign Language""")
    APAASCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Vocational GCSE Additional Applied Science""")
    APADTSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in GCSE Additional Science""")
    APAPDSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in GCSE Applied Science""")
    APARA = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Arabic.""")
    APART = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Art and Design.""")
    APBEN = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Bengali.""")
    APBHEB = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE (including Double Awards where appropriate) Biblical Hebrew.""")
    APBIO = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Biological Science.""")
    APBIOE = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE (including Double Awards where appropriate) Biology (except Human Biology)""")
    APBUS = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Business Studies.""")
    APCGRK = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE (including Double Awards where appropriate) Classical Greek.""")
    APCHE = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Chemistry.""")
    APCHI = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Chinese.""")
    APCORESCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in GCSE Core Science""")
    APDAN = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Danish.""")
    APDRA = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Drama.""")
    APDSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Double Award Science.""")
    APDTT = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE (including Double Awards where appropriate) Design and Technology: Textiles Technology.""")
    APDUT = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Dutch.""")
    APELANG = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE English Language. No qualifications have been awarded in this subject since 2006, they are now all included in APENG""")
    APELEC = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE (including Double Awards where appropriate) Design and Technology: Electronic Products.""")
    APELIT = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE English Literature.""")
    APENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE English.""")
    APFINE = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Fine Art.""")
    APFOOD = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE (including Double Awards where appropriate) Design and Technology: Food Technology.""")
    APFRE = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE French.""")
    APGEO = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Geography.""")
    APGER = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE German.""")
    APGRA = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE (including Double Awards where appropriate) Design and Technology: Graphic Products.""")
    APGUJ = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Gujarati.""")
    APHECD = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Home Economics: Child Development.""")
    APHIN = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Hindi.""")
    APHIS = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE History.""")
    APHSC = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Vocational GCSE Health and Social Care.""")
    APIT = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Information Technology.""")
    APITA = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Italian.""")
    APITSC = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Short GCSE Information Technology.""")
    APJAP = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Japanese.""")
    APLAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE (including Double Awards where appropriate) Latin.""")
    APLT = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Vocational GCSE Leisure and Tourism.""")
    APMAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Maths.""")
    APMFT = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Media, Film and Television Studies.""")
    APMGRK = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Modern Greek.""")
    APMHEB = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Modern Hebrew.""")
    APMUS = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Music.""")
    APOFT = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Office Technology.""")
    APPAN = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Panjabi.""")
    APPE = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Physical Education.""")
    APPER = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Persian.""")
    APPHY = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Physics.""")
    APPOL = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Polish.""")
    APPOR = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Portuguese.""")
    APRE = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Short GCSE Religious Studies.""")
    APRES = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE (including Double Awards where appropriate) Design and Technology: Resistant Materials Technology.""")
    APRS = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Religious Studies.""")
    APRUS = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Russian.""")
    APSPAN = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Spanish.""")
    APSSC = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Short GCSE Social Science Citizenship.""")
    APSSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Single Award Science.""")
    APSTAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Statistics.""")
    APSVSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Vocational GCSE Single Award Additional Applied Science.""")
    APSYS = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE (including Double Awards where appropriate) Design and Technology: Systems & Control.""")
    APTUR = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Turkish.""")
    APURD = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Full GCSE Urdu.""")
    APVBUS = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Vocational GCSE Double Award Applied Business.""")
    APVIT = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Vocational GCSE Double Award Applied ICT.""")
    APVSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in Vocational GCSE Double Award Applied Science.""")
    APVSL = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in VRQ Sports Leadership""")
    AVPTSENT = models.CharField(max_length="10", blank=True, null=True, help_text="""Average GCSE and equivalent point score per entry""")
    BTEC = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of BTEC First Diploma/Certificates achieved (NOT GCSE equivalencies).""")
    BTECAPPSCI_CERS = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in BTEC Applied Sciences - first certificate starred distinction grading""")
    BTECAPPSCI_DIPS = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in BTEC Applied Sciences - first diploma starred distinction grading""")
    BTECENG_CERS = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in BTEC Engineering studies - first certificate starred distinction grading""")
    BTECENG_DIPS = models.CharField(max_length="10", blank=True, null=True, help_text="""Grade achieved in BTEC Engineering studies - first diploma starred distinction grading""")
    EBAC2SCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved EBacc 2 sciences component""")
    EBAC2SCIAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved EBacc 2 sciences component at grade A*-G""")
    EBAC2SCI_E = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil entered for Ebacc science (i.e. 3 separate sciences, Core plus additional or double science)""")
    EBACC = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved English Baccalaureate - A*-C passes in English, mathematics, 2 sciences, a humanity and a language""")
    EBACCAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved English Baccalaureate - A*-G passes in English, mathematics, 2 sciences, a humanity and a language""")
    EBACC_E = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered all subject pillars of the Ebacc""")
    EBACENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved EBacc English component""")
    EBACENGAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved EBacc English component at A*-G""")
    EBACENG_E = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil entered for Ebacc English""")
    EBACHUM = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved EBacc Humanities component""")
    EBACHUMAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved EBacc Humanities component at grades A*-G""")
    EBACHUM_E = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil entered for Ebacc Humanities (Geography or History)""")
    EBACLAN = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved EBacc language component""")
    EBACLANAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved EBacc language component at grades A*-G""")
    EBACLAN_E = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil entered for Ebacc Languages""")
    EBACMAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved EBacc maths component""")
    EBACMATAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved EBacc maths component at grades A*-G""")
    EBACMAT_E = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil entered for Ebacc Maths""")
    EBALLSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered all of Biology, Physics and Chemistry GCSE """)
    EBPTSENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Point score in English EBacc pillar""")
    EBPTSHUM = models.CharField(max_length="10", blank=True, null=True, help_text="""Highest point score achieved in humanities Ebacc pillar""")
    EBPTSLAN = models.CharField(max_length="10", blank=True, null=True, help_text="""Highest point score achieved in language Ebacc pillar""")
    EBPTSMAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Point score in maths EBacc pillar""")
    EBPTSSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Point score in science Ebacc pillar""")
    EDEXDA = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of EDEXCEL Qualifications in Digital Applications for IT Users achieved (NOT GCSE equivalencies).""")
    ELQENTS = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Entry Level Qualification entries.""")
    ELQONLY = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved ELQs only""")
    ELQPASS = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Entry Level Qualification passes.""")
    ENDKS = models.CharField(max_length="10", blank=True, null=True, help_text="""Indicates whether a pupil is at the end of KS4""")
    ENGPAIR = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil entered for English Language and English Literature linked pair GCSEs""")
    ENGPAIRLEV1 = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved level 2 GCSE in English Language in the English linked pairs""")
    ENGPAIRLEV2 = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved level 1 GCSE in English language in English linked pairs""")
    ENT1EMFL = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered for at least 1 Modern Foreign Language qualification.""")
    ENT1GMFL = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered for at least 1 Full GCSE Modern Foreign Language qualification.""")
    ENTRIES = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of entries.""")
    ENTRY_1 = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil entered for at least 1 GCSE or equivalent""")
    ENTRY_5 = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil entered for 5 or more GCSE or equivalent""")
    ENTRY_E = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of GCSE and equivalents entries (GCSE equivalencies).""")
    ENTRY_G = models.CharField(max_length="10", blank=True, null=True, help_text=""""Total number of GCSE/GNVQ entries (GCSE equivalencies) - from 2001/2002 to 2009/2010 Total number of GCSE only entries (GCSE equivalencies) - from 2010/2011.""")
    EXAMCAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Highest examination category achieved at GCSE and equivalent.""")
    FIVEAC = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 5 or more GCSE/GNVQs at grades A*-C.""")
    FIVEAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 5 or more GCSE/GNVQs at grades A*-G.""")
    Flag24ENGPrg = models.CharField(max_length="10", blank=True, null=True, help_text="""Flag to indicate that the pupil has achieved expected progress in English  between KS2 and KS4 (2011 methodology)""")
    Flag24MATPrg = models.CharField(max_length="10", blank=True, null=True, help_text="""Flag to indicate that the pupil has achieved expected progress in mathematics between KS2 and KS4 (2011 methodology)""")
    FLAG3GENG24 = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 3 levels of progress from KS2 (excluding TA) to GCSE English at KS4""")
    FLAG3GMATH24 = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 3 levels of progress from KS2 (excluding TA) to GCSE Maths at KS4""")
    GCSEENG = models.CharField(max_length="10", blank=True, null=True, help_text="""The highest point score achieved in English (old point score)""")
    GCSEFULL = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Full GCSE entries.""")
    GCSEMATH = models.CharField(max_length="10", blank=True, null=True, help_text="""The highest point score achieved in Maths (old point score)""")
    GCSESCI = models.CharField(max_length="10", blank=True, null=True, help_text="""The highest point score achieved in Science (old point score)""")
    GCSESHORT = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Short GCSE entries.""")
    GCSEVOC = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Double Award Vocational GCSE entries.""")
    GCSE_A = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Full GCSE qualifications at grade A (GCSE equivalencies).""")
    GCSE_AA = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Full GCSE qualifications at grades A*-A (GCSE equivalencies).""")
    GCSE_AC = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Full GCSE qualifications at grades A*-C (GCSE equivalencies).""")
    GCSE_AG = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Full GCSE qualifications at grades A*-G (GCSE equivalencies).""")
    GCSE_ASTAR = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Full GCSE qualifications at grade A* (GCSE equivalencies).""")
    GCSE_B = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Full GCSE qualifications at grade B (GCSE equivalencies).""")
    GCSE_C = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Full GCSE qualifications at grade C (GCSE equivalencies).""")
    GCSE_D = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Full GCSE qualifications at grade D (GCSE equivalencies).""")
    GCSE_DG = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Full GCSE qualifications at grades D-G (GCSE equivalencies).""")
    GCSE_E = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Full GCSE qualifications at grade E (GCSE equivalencies).""")
    GCSE_ENGAC = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil passed English GCSE at A* - C""")
    GCSE_ENGAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil passed English GCSE at A* - G""")
    GCSE_ENGATT = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil attempted English GCSE""")
    GCSE_F = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Full GCSE qualifications at grade F (GCSE equivalencies).""")
    GCSE_G = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Full GCSE qualifications at grade G (GCSE equivalencies).""")
    GCSE_MATHAC = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil passed Maths GCSE at A* - C""")
    GCSE_MATHAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil passed Maths GCSE at A* - G""")
    GCSE_MATHATT = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil attempted Maths GCSE""")
    GCSE_SCIAC = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil passed Science GCSE at A* - C""")
    GCSE_SCIAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil passed Science GCSE at A* - G""")
    GCSE_SCIATT = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil attempted Science GCSE""")
    GCSE_SHORT_A = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Short GCSE qualifications at grade A (GCSE equivalencies).""")
    GCSE_SHORT_AA = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Short GCSE qualifications at grades A*-A (GCSE equivalencies).""")
    GCSE_SHORT_AC = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Short GCSE qualifications at grades A*-C (GCSE equivalencies).""")
    GCSE_SHORT_AG = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Short GCSE qualifications at grades A*-G (GCSE equivalencies).""")
    GCSE_SHORT_ASTAR = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Short GCSE qualifications at grade A* (GCSE equivalencies).""")
    GCSE_SHORT_B = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Short GCSE qualifications at grade B (GCSE equivalencies).""")
    GCSE_SHORT_C = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Short GCSE qualifications at grade C (GCSE equivalencies).""")
    GCSE_SHORT_D = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Short GCSE qualifications at grade D (GCSE equivalencies).""")
    GCSE_SHORT_DG = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Short GCSE qualifications at grades D-G (GCSE equivalencies).""")
    GCSE_SHORT_E = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Short GCSE qualifications at grade E (GCSE equivalencies).""")
    GCSE_SHORT_F = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Short GCSE qualifications at grade F (GCSE equivalencies).""")
    GCSE_SHORT_G = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Short GCSE qualifications at grade G (GCSE equivalencies).""")
    GCSE_U = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Full GCSE qualifications at grade U (GCSE equivalencies).""")
    GLEVEL2 = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 5 A*-C (GCSE only, including Applied)""")
    GLEVEL2EM = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 5 A*-C including English and maths (GCSE only, including Applied)""")
    GNVQFOUDIS = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Distinction Foundation GNVQs (GCSE equivalencies).""")
    GNVQFOUMER = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Merit Foundation GNVQs (GCSE equivalencies).""")
    GNVQFOUPAS = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Pass Foundation GNVQs (GCSE equivalencies).""")
    GNVQFULLF = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Full Foundation GNVQ entries.""")
    GNVQFULLI = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Full Intermediate GNVQ entries.""")
    GNVQINTDIS = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Distinction Intermediate GNVQs (GCSE equivalencies).""")
    GNVQINTMER = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Merit Intermediate GNVQs (GCSE equivalencies).""")
    GNVQINTPAS = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Pass Intermediate GNVQs (GCSE equivalencies).""")
    GNVQLANGF = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Language Foundation GNVQ entries.""")
    GNVQLANGI = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Language Intermediate GNVQ entries.""")
    GNVQP1F = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Part One Foundation GNVQ entries.""")
    GNVQP1I = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Part One Intermediate GNVQ entries.""")
    GPTSCNEWE = models.CharField(max_length="10", blank=True, null=True, help_text="""Capped GCSE point score excluding equivalents""")
    GVOC_A = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Double Award Vocational GCSE qualifications at grade AA (GCSE equivalencies).""")
    GVOC_AA = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Double Award Vocational GCSE qualifications at grades A*A*-AA (GCSE equivalencies).""")
    GVOC_AC = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Double Award Vocational GCSE qualifications at grades A*A*-CC (GCSE equivalencies).""")
    GVOC_AG = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Double Award Vocational GCSE qualifications at grades A*A*-GG (GCSE equivalencies).""")
    GVOC_ASTAR = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Double Award Vocational GCSE qualifications at grade A*A* (GCSE equivalencies).""")
    GVOC_B = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Double Award Vocational GCSE qualifications at grade BB (GCSE equivalencies).""")
    GVOC_C = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Double Award Vocational GCSE qualifications at grade CC (GCSE equivalencies).""")
    GVOC_D = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Double Award Vocational GCSE qualifications at grade DD (GCSE equivalencies).""")
    GVOC_DG = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Double Award Vocational GCSE qualifications at grades DD-GG (GCSE equivalencies).""")
    GVOC_E = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Double Award Vocational GCSE qualifications at grade EE (GCSE equivalencies).""")
    GVOC_F = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Double Award Vocational GCSE qualifications at grade FF (GCSE equivalencies).""")
    GVOC_G = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of Double Award Vocational GCSE qualifications at grade GG (GCSE equivalencies).""")
    HGMATH = models.CharField(max_length="10", blank=True, null=True, help_text="""Highest grade achieved in Full GCSE Maths (as used in the Maths threshold measures).""")
    HPGENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Highest standardised points in English GCSE""")
    HPGMATH = models.CharField(max_length="10", blank=True, null=True, help_text="""Highest standardised points in Maths GCSE""")
    KS4SCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Highest point score achieved (GCSE equivalencies) in Science (Full GCSE, Full Intermediate or Foundation GNVQ and Vocational GCSE)""")
    KSL1ENTS = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Key Skills at Level 1entries.""")
    KSL1PASS = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Key Skills at Level 1 passes.""")
    KSL2ENTS = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Key Skills at Level 2 entries.""")
    KSL2PASS = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Key Skills at Level 2 passes.""")
    L2BASICS = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved English and Maths GCSEs or iGCSEs at Level 2""")
    LEV1EM = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-G in GCSE English and Maths.""")
    LEV1ENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-G in GCSE English.""")
    LEV1FEM = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-G in GCSE and equivalents English and Maths (Functional English and Maths).""")
    LEV1FENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-G in GCSE and equivalents English (Functional English).""")
    LEV1FMAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-G in GCSE and equivalents Maths (Functional Maths).""")
    LEV1MAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-G in GCSE Maths.""")
    LEV2EM = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-C in GCSE English and Maths.""")
    LEV2ENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-C in GCSE English.""")
    LEV2FEM = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-C in GCSE and equivalents English and Maths (Functional English and Maths). """)
    LEV2FENG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-C in GCSE and equivalents English (Functional English). """)
    LEV2FMAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-C in GCSE and equivalents Maths (Functional Maths). """)
    LEV2MAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-C in GCSE Maths.""")
    LEV2SCI2 = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 2 'good' science GCSEs or equivalent.""")
    LEV2SCI2B = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 2 'good' science GCSEs or equiv (counting the BTECs and OCRs).""")
    LEV2SCIA = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Double science or Applied Science.""")
    LEV2SCIB = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved GCSE Science plus GCSE Additional Science or Applied Science or GCSE Land & Environment.""")
    LEV2SCIC = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered Biology, Physics, Chemistry  GCSEs or ASs and achieved 'good' Biology plus Physics or Chemistry  GCSEs or ASs.""")
    LEV2SCID = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered Biology, Physics, Chemistry  GCSEs or ASs and achieved 'good' Physics and Chemistry  GCSEs or ASs.""")
    LEV2SCIE = models.CharField(max_length="10", blank=True, null=True, help_text="""BTECs in Science.""")
    LEV2SCIF = models.CharField(max_length="10", blank=True, null=True, help_text="""OCR Nationals Award and Certificate in Science.""")
    LEV2SCIG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved equivalent of Level 2 in Intermediate GNVQs in Science""")
    LEVEL1 = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 1 threshold (5 or more GCSE and equivalents at grades A*-G).""")
    LEVEL1MFL = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-G in one short course Modern Foreign Language GCSE or equivalent """)
    LEVEL1_EM = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 5 or more GCSE and equivalents at grades A*-G including GCSE English and Maths.""")
    LEVEL1_FEM = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 5 or more GCSE and equivalents at grades A*-G including GCSE and equivalents in English and Maths (Functional English and Maths).""")
    LEVEL2 = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved Level 2 threshold (5 or more GCSE and equivalents at grades A*-C). """)
    LEVEL2EM_GCSE = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 5 or more GCSEs (excluding equivalents) at A*-C including GCSE English and Maths""")
    LEVEL2MFL = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-C in one full Modern Foreign Language GCSE or equivalent""")
    LEVEL2_EM = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 5 or more GCSE and equivalents at grades A*-C including GCSE English and Maths.""")
    LEVEL2_FEM = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 5 or more GCSE and equivalents at grades A*-C including GCSE and equivalents in English and Maths (Functional English and Maths).""")
    MATHPAIR = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered 'Applications of mathematics' and 'Methods in mathematics' GCSEs""")
    NOPASSES = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved no passes at all (inc S96)""")
    PASS2SCIA = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered Biology, Physics, Chemistry GCSEs and achieved 'good' Biology plus Physics or Chemistry """)
    PASS2SCIAAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered Biology, Physics, Chemistry GCSEs and achieved A*-G Biology plus Physics or Chemistry """)
    PASS2SCIB = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered Biology, Physics, Chemistry GCSEs and achieved 'good' Physics and Chemistry """)
    PASS2SCIBAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered Biology, Physics, Chemistry GCSEs and achieved A*-G Physics and Chemistry """)
    PASSMATHPR = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved at least a Grade C in one of the Maths linked pair GCSEs""")
    PASSMATHPRAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved at least a Grade G in one of the Maths linked pair GCSEs""")
    PASSOTHSCI = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved double science or Core and Additional science """)
    PASSOTHSCIAG = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved double science or Core and Additional science at grades A*-G""")
    PASS_1AC = models.CharField(max_length="10", blank=True, null=True, help_text="""Pupil passed at least one level 2 qualification""")
    PASS_AASTAR = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of GCSE/GNVQ qualifications at grades A*-A (GCSE equivalencies).""")
    PASS_AASTAR5 = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved 5 or more GCSE/GNVQs at grades A*-A.""")
    PASS_ABSCI2 = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved equivalent of A*-B GCSE in 2 Science GCSEs or equiv""")
    PASS_ABSCI2B = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved equivalent of A*-B GCSE in 2 Science GCSEs or equiv (including the BTECs and OCRs)""")
    PASS_ABSCIA = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-B in Double Science or Applied Science""")
    PASS_ABSCIB = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved A*-B in GCSE Science plus GCSE Additional Science or Applied Science or GCSE Land & Environment""")
    PASS_ABSCIC = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered Biology, Physics, Chemistry GCSEs or ASs and achieved equivalent of A*-B GCSE in Biology plus Physics or Chemistry GCSEs or ASs""")
    PASS_ABSCID = models.CharField(max_length="10", blank=True, null=True, help_text="""Entered Biology, Physics, Chemistry GCSEs or ASs and achieved equivalent of A*-B GCSE in Physics and Chemistry GCSEs or ASs""")
    PASS_ABSCIE = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved equivalent of A*-B GCSE in BTECs in Science""")
    PASS_ABSCIF = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved equivalent of A*-B GCSE in OCR Nationals Award and Certificate in Science""")
    PASS_ABSCIG = models.CharField(max_length="10", blank=True, null=True, help_text="""IGNVQ science""")
    PASS_AC = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of GCSE/GNVQ qualifications at grades A*-C (GCSE equivalencies).""")
    PASS_AC5EM = models.CharField(max_length="10", blank=True, null=True, help_text="""5+A*C including English and Maths GCSE/GNVQ""")
    PASS_AC_AAT = models.CharField(max_length="10", blank=True, null=True, help_text="""Number of passes at grades A*-C  (equivalents included).""")
    PASS_AG = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of GCSE qualifications at grades  A*-G (GCSE equivalencies).""")
    PASS_LEV1 = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Level 1 GCSE and equivalent qualifications (GCSE equivalencies).""")
    PASS_LEV1EM = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of level 1 GCSE and equivalent qualifications including Leve1 1 in GCSE English and Maths (GCSE equivalencies).""")
    PASS_LEV2 = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Level 2 GCSE and equivalent qualifications (GCSE equivalencies).""")
    PASS_LEV2EM = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Level 2 GCSE and equivalent qualifications including Level2 in GCSE English and Maths  (GCSE equivalencies).""")
    POINTS_OLD_G = models.CharField(max_length="10", blank=True, null=True, help_text="""Total GCSE/GNVQ old style point score.""")
    PTSCNEWE = models.CharField(max_length="10", blank=True, null=True, help_text="""Capped GCSE and equivalents new style point score.""")
    PTSTNEWE = models.CharField(max_length="10", blank=True, null=True, help_text="""Total GCSE and equivalents new style point score.""")
    PTSTNEWG = models.CharField(max_length="10", blank=True, null=True, help_text="""Total GCSE/GNVQ new style point score.""")
    PTSTOLDG = models.CharField(max_length="10", blank=True, null=True, help_text="""Total GCSE/GNVQ  old style point score""")
    TOTGNVQFOU = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Foundation GNVQ qualifications (GCSE equivalencies).""")
    TOTGNVQINT = models.CharField(max_length="10", blank=True, null=True, help_text="""Total number of Intermediate GNVQ qualifications (GCSE equivalencies).""")
    VOCQUAL = models.CharField(max_length="10", blank=True, null=True, help_text="""Achieved at least one vocational qualification at KS4. """)
    
class KS5(PupilData):
    pass


class Dummy(models.Model):
    """
    A dummy model for testing
    """
    public = models.CharField(blank=True, max_length=100)
    private = models.CharField(blank=True, max_length=100)
    
